Traceback (most recent call last):
  File "/home/hs20307/tls-rl/rl.py", line 91, in <module>
    main()
  File "/home/hs20307/tls-rl/rl.py", line 68, in main
    next_state, reward, done = env.step(action)
  File "/home/hs20307/tls-rl/environment.py", line 31, in step
    new_word = self.vocab[action]
KeyError: 77199
